### ISSUE TITLE
Edit ontology title of MFOMD

### ISSUE THREAD

**Issue by simonjupp** [jannahastings/mental-functioning-ontology#3]
In the OWL file for MFOMD you have

```
        <dc:title>The Mental Disease Ontology was first described in the publication &apos;Foundations for a realist ontology of mental disease&apos; (Barry Smith and Werner Ceusters) which is available at http://www.jbiomedsem.com/content/1/1/10 . </dc:title>
```

Do you really want that to be the title of your ontology? OLS is respecting your dc:title tag, but it doesn't look great n the browser. 

http://www.ebi.ac.uk/ols/beta/ontologies/mfomd

Do you think you could change it to something shorter?

**Comment by phismith** [comment]
I think this must be a typo. To my mind the title has always been 'MFO'
Janna: can you fix?
BS
