### ISSUE TITLE
Is this ontology still active?

### ISSUE THREAD

**Issue by cmungall** [jannahastings/mental-functioning-ontology#4]
@jannahastings - did you pass on ownership of this ontology?

Note that it has not been parseable by the OWLAPI, probably since google code shut down: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/410#issuecomment-296842404

If it can't be repaired we'll have to tag it as obsolete

cc @phismith

**Comment by jannahastings** [comment]
Yes, still active. Sorry, will fix the missing import now...

**Comment by jannahastings** [comment]
OGMS import fixed and now it gives no errors in Protege, @cmungall does it work for you now?

**Comment by cmungall** [comment]
Thx!
